version: "2.1"

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
